import type { CardFormField } from "./form_fields";

// Contains all card types and which form fields should be shown for each type.
export const CardTypes: Record<string, readonly CardFormField[]> = {
	action: [
		"CardPitch",
		"CardName",
		"CardResource",
		"CardText",
		"CardPower",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardSubType",
		"CardRarity",
		"CardDefense",
		"CardLife",
	],
	attack_reaction: [
		"CardPitch",
		"CardName",
		"CardResource",
		"CardText",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardSubType",
		"CardRarity",
		"CardDefense",
	],
	block: [
		"CardPitch",
		"CardName",
		"CardText",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardSubType",
		"CardRarity",
		"CardDefense",
	],
	defense_reaction: [
		"CardPitch",
		"CardName",
		"CardResource",
		"CardText",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardSubType",
		"CardRarity",
		"CardDefense",
	],
	demi_hero: [
		"CardName",
		"CardText",
		"CardHeroIntellect",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardSubType",
		"CardLife",
		"CardRarity",
	],
	equipment: [
		"CardName",
		"CardText",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardSubType",
		"CardRarity",
		"CardDefense",
	],
	hero: [
		"CardName",
		"CardText",
		"CardHeroIntellect",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardSubType",
		"CardLife",
		"CardRarity",
	],
	instant: [
		"CardPitch",
		"CardName",
		"CardResource",
		"CardText",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardSubType",
		"CardRarity",
		"CardDefense",
	],
	macro: ["CardName", "CardText", "CardRarity", "CardSubType"],
	mentor: [
		"CardName",
		"CardText",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardRarity",
		"CardDefense",
		"CardSubType",
	],
	resource: [
		"CardPitch",
		"CardName",
		"CardText",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardSubType",
		"CardRarity",
	],
	token: [
		"CardName",
		"CardText",
		"CardPower",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardLife",
		"CardSubType",
		"CardRarity",
	],
	weapon: [
		"CardName",
		"CardText",
		"CardPower",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardWeapon",
		"CardRarity",
		"CardSubType",
	],
	weapon_equipment: [
		"CardName",
		"CardText",
		"CardPower",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardSubType",
		"CardWeapon",
		"CardDefense",
		"CardRarity",
	],
	ally: [
		"CardName",
		"CardText",
		"CardPower",
		"CardTalent",
		"CardClass",
		"CardSecondaryClass",
		"CardLife",
		"CardRarity",
		"CardSubType",
	],
	event: [
		"CardName",
		"CardText",
		"CardPower",
		"CardClass",
		"CardSecondaryClass",
		"CardRarity",
		"CardSubType",
	],
};

// Utility type for string representation of each card type.
export type CardType = keyof typeof CardTypes;
